LIB_SRCS += \
    libjingle-0.6.14/talk/base/asyncfile.cc\
	libjingle-0.6.14/talk/base/asynchttprequest.cc\
	libjingle-0.6.14/talk/base/asyncsocket.cc\
	libjingle-0.6.14/talk/base/asynctcpsocket.cc\
	libjingle-0.6.14/talk/base/asyncudpsocket.cc\
	libjingle-0.6.14/talk/base/autodetectproxy.cc\
	libjingle-0.6.14/talk/base/bandwidthsmoother.cc\
	libjingle-0.6.14/talk/base/base64.cc\
	libjingle-0.6.14/talk/base/basicpacketsocketfactory.cc\
	libjingle-0.6.14/talk/base/bytebuffer.cc\
	libjingle-0.6.14/talk/base/checks.cc\
	libjingle-0.6.14/talk/base/common.cc\
	libjingle-0.6.14/talk/base/cpuid.cc\
	libjingle-0.6.14/talk/base/cpumonitor.cc\
	libjingle-0.6.14/talk/base/diskcache.cc\
	libjingle-0.6.14/talk/base/event.cc\
	libjingle-0.6.14/talk/base/filelock.cc\
	libjingle-0.6.14/talk/base/fileutils.cc\
	libjingle-0.6.14/talk/base/firewallsocketserver.cc\
	libjingle-0.6.14/talk/base/flags.cc\
	libjingle-0.6.14/talk/base/helpers.cc\
	libjingle-0.6.14/talk/base/host.cc\
	libjingle-0.6.14/talk/base/httpbase.cc\
	libjingle-0.6.14/talk/base/httpclient.cc\
	libjingle-0.6.14/talk/base/httpcommon.cc\
	libjingle-0.6.14/talk/base/httprequest.cc\
	libjingle-0.6.14/talk/base/httpserver.cc\
	libjingle-0.6.14/talk/base/ipaddress.cc\
	libjingle-0.6.14/talk/base/logging.cc\
	libjingle-0.6.14/talk/base/md5c.cc\
	libjingle-0.6.14/talk/base/messagehandler.cc\
	libjingle-0.6.14/talk/base/messagequeue.cc\
	libjingle-0.6.14/talk/base/multipart.cc\
	libjingle-0.6.14/talk/base/natserver.cc\
	libjingle-0.6.14/talk/base/natsocketfactory.cc\
	libjingle-0.6.14/talk/base/nattypes.cc\
	libjingle-0.6.14/talk/base/nethelpers.cc\
	libjingle-0.6.14/talk/base/network.cc\
	libjingle-0.6.14/talk/base/openssladapter.cc\
	libjingle-0.6.14/talk/base/optionsfile.cc\
	libjingle-0.6.14/talk/base/pathutils.cc\
	libjingle-0.6.14/talk/base/physicalsocketserver.cc\
	libjingle-0.6.14/talk/base/proxydetect.cc\
	libjingle-0.6.14/talk/base/proxyinfo.cc\
	libjingle-0.6.14/talk/base/proxyserver.cc\
	libjingle-0.6.14/talk/base/ratetracker.cc\
	libjingle-0.6.14/talk/base/sharedexclusivelock.cc\
	libjingle-0.6.14/talk/base/signalthread.cc\
	libjingle-0.6.14/talk/base/socketadapters.cc\
	libjingle-0.6.14/talk/base/socketaddress.cc\
	libjingle-0.6.14/talk/base/socketaddresspair.cc\
	libjingle-0.6.14/talk/base/socketpool.cc\
	libjingle-0.6.14/talk/base/socketstream.cc\
	libjingle-0.6.14/talk/base/ssladapter.cc\
	libjingle-0.6.14/talk/base/sslsocketfactory.cc\
	libjingle-0.6.14/talk/base/stream.cc\
	libjingle-0.6.14/talk/base/stringdigest.cc\
	libjingle-0.6.14/talk/base/stringencode.cc\
	libjingle-0.6.14/talk/base/stringutils.cc\
	libjingle-0.6.14/talk/base/systeminfo.cc\
	libjingle-0.6.14/talk/base/task.cc\
	libjingle-0.6.14/talk/base/taskparent.cc\
	libjingle-0.6.14/talk/base/taskrunner.cc\
	libjingle-0.6.14/talk/base/testclient.cc\
	libjingle-0.6.14/talk/base/thread.cc\
	libjingle-0.6.14/talk/base/timeutils.cc\
	libjingle-0.6.14/talk/base/timing.cc\
	libjingle-0.6.14/talk/base/transformadapter.cc\
	libjingle-0.6.14/talk/base/urlencode.cc\
	libjingle-0.6.14/talk/base/versionparsing.cc\
	libjingle-0.6.14/talk/base/virtualsocketserver.cc\
	libjingle-0.6.14/talk/base/worker.cc\
	libjingle-0.6.14/talk/p2p/base/constants.cc\
	libjingle-0.6.14/talk/p2p/base/p2ptransport.cc\
	libjingle-0.6.14/talk/p2p/base/p2ptransportchannel.cc\
	libjingle-0.6.14/talk/p2p/base/parsing.cc\
	libjingle-0.6.14/talk/p2p/base/port.cc\
	libjingle-0.6.14/talk/p2p/base/portallocator.cc\
	libjingle-0.6.14/talk/p2p/base/portallocatorsessionproxy.cc\
	libjingle-0.6.14/talk/p2p/base/portproxy.cc\
	libjingle-0.6.14/talk/p2p/base/pseudotcp.cc\
	libjingle-0.6.14/talk/p2p/base/relayport.cc\
	libjingle-0.6.14/talk/p2p/base/relayserver.cc\
	libjingle-0.6.14/talk/p2p/base/rawtransport.cc\
	libjingle-0.6.14/talk/p2p/base/rawtransportchannel.cc\
	libjingle-0.6.14/talk/p2p/base/session.cc\
	libjingle-0.6.14/talk/p2p/base/sessiondescription.cc\
	libjingle-0.6.14/talk/p2p/base/sessionmanager.cc\
	libjingle-0.6.14/talk/p2p/base/sessionmessages.cc\
	libjingle-0.6.14/talk/p2p/base/stun.cc\
	libjingle-0.6.14/talk/p2p/base/stunport.cc\
	libjingle-0.6.14/talk/p2p/base/stunrequest.cc\
	libjingle-0.6.14/talk/p2p/base/stunserver.cc\
	libjingle-0.6.14/talk/p2p/base/tcpport.cc\
	libjingle-0.6.14/talk/p2p/base/transport.cc\
	libjingle-0.6.14/talk/p2p/base/transportchannel.cc\
	libjingle-0.6.14/talk/p2p/base/transportchannelproxy.cc\
	libjingle-0.6.14/talk/p2p/base/udpport.cc\
	libjingle-0.6.14/talk/p2p/client/basicportallocator.cc\
	libjingle-0.6.14/talk/p2p/client/connectivitychecker.cc\
	libjingle-0.6.14/talk/p2p/client/httpportallocator.cc\
	libjingle-0.6.14/talk/p2p/client/socketmonitor.cc\
	libjingle-0.6.14/talk/session/tunnel/pseudotcpchannel.cc\
	libjingle-0.6.14/talk/session/tunnel/tunnelsessionclient.cc\
	libjingle-0.6.14/talk/session/tunnel/securetunnelsessionclient.cc\
	libjingle-0.6.14/talk/xmllite/qname.cc\
	libjingle-0.6.14/talk/xmllite/xmlbuilder.cc\
	libjingle-0.6.14/talk/xmllite/xmlconstants.cc\
	libjingle-0.6.14/talk/xmllite/xmlelement.cc\
	libjingle-0.6.14/talk/xmllite/xmlnsstack.cc\
	libjingle-0.6.14/talk/xmllite/xmlparser.cc\
	libjingle-0.6.14/talk/xmllite/xmlprinter.cc\
	libjingle-0.6.14/talk/xmpp/constants.cc\
	libjingle-0.6.14/talk/xmpp/hangoutpubsubclient.cc\
	libjingle-0.6.14/talk/xmpp/iqtask.cc\
	libjingle-0.6.14/talk/xmpp/jid.cc\
	libjingle-0.6.14/talk/xmpp/moduleimpl.cc\
	libjingle-0.6.14/talk/xmpp/mucroomconfigtask.cc\
	libjingle-0.6.14/talk/xmpp/mucroomhistorytask.cc\
	libjingle-0.6.14/talk/xmpp/mucroomlookuptask.cc\
	libjingle-0.6.14/talk/xmpp/pubsubclient.cc\
	libjingle-0.6.14/talk/xmpp/pubsub_task.cc\
	libjingle-0.6.14/talk/xmpp/pubsubtasks.cc\
	libjingle-0.6.14/talk/xmpp/receivetask.cc\
	libjingle-0.6.14/talk/xmpp/saslmechanism.cc\
	libjingle-0.6.14/talk/xmpp/xmppclient.cc\
	libjingle-0.6.14/talk/xmpp/xmppengineimpl.cc\
	libjingle-0.6.14/talk/xmpp/xmppengineimpl_iq.cc\
	libjingle-0.6.14/talk/xmpp/xmpplogintask.cc\
	libjingle-0.6.14/talk/xmpp/xmppstanzaparser.cc\
	libjingle-0.6.14/talk/xmpp/xmpptask.cc\
	libjingle-0.6.14/talk/base/latebindingsymboltable.cc\
	libjingle-0.6.14/talk/base/linux.cc\
	libjingle-0.6.14/talk/base/linuxfdwalk.cc\
	libjingle-0.6.14/talk/base/libdbusglibsymboltable.cc\
	libjingle-0.6.14/talk/base/unixfilesystem.cc\
	libjingle-0.6.14/talk/base/opensslidentity.cc\
	libjingle-0.6.14/talk/base/opensslstreamadapter.cc\
	libjingle-0.6.14/talk/base/posix.cc\
	libjingle-0.6.14/talk/base/sslidentity.cc\
	libjingle-0.6.14/talk/base/sslstreamadapter.cc\
	libjingle-0.6.14/talk/examples/login/jingleinfotask.cc\
	libjingle-0.6.14/talk/examples/login/xmppauth.cc\
	libjingle-0.6.14/talk/examples/login/xmpppump.cc\
	libjingle-0.6.14/talk/examples/login/xmppsocket.cc\
